
services:
  api-rest-meli:
    build:
      dockerfile: Dockerfile
    container_name: api-rest-app
    ports:
      - "8080:8080"
    environment:
      - spring.security.userclient.token=e962f81a-4d42-4eb3-86cd-a25e7237c8dc
      - spring.security.usermock.token=55a4639f-55e8-4e14-a6cc-b79977b20a4e
    networks:
      - api-network

networks:
  api-network:
    driver: bridge